
expDistance:
  - overWorld:
    - 300:
       0
    - 450:
       5
    - 600:
       10
    - 750:
       15
    - 900:
       20
    - 1050:
       25
    - 1200:
       30
    - 1350:
       35
    - 1500:
       40
    - 1650:
       45
    - 1800:
       50
    - 1950:
       55
    - 2100:
       60
    - 2250:
       65
    - 2400:
       70
    - 2550:
       75
    - 2700:
       80
    - 2850:
       85
    - 3000:
       90
    - 3150:
       95
  - nether:
    - 200:
        10
    - 300:
        20.0
    - 400:
        25.0
    - 500:
        30.0
    - 600:
        35.0
    - 700:
        40.0
    - 800:
        45.0
    - 900:
        50.0
    - 1000:
        55.0
    - 1100:
        60.0
    - 1200:
        65.0
    - 1300:
        70.0
    - 1400:
        75.0
    - 1500:
        80.0
    - 1600:
        85.0
    - 1700:
       90.0
    - 1800:
        95.0
    - 1900:
        100.0
    - 2000:
        105.0
    - 2100:
        110.0
  - end:
    - 10:
        100
level:
  - 0: 15
  - 1: 30
  - 2: 45
  - 3: 60
  - 4: 75
  - 5: 90
  - 6: 105
  - 7: 120
  - 8: 135
  - 9: 150
  - 10: 180
  - 11: 210
  - 12: 240
  - 13: 270
  - 14: 300
  - 15: 330
  - 16: 360
  - 17: 390
  - 18: 420
  - 19: 450
  - 20: 480
  - 21: 540
  - 22: 600
  - 23: 660
  - 24: 720
  - 25: 780
  - 26: 840
  - 27: 900
  - 28: 960
  - 29: 1020
  - 30: 1080
  - 31: 1170
  - 32: 1260
  - 33: 1350
  - 34: 1440
  - 35: 1530
  - 36: 1620
  - 37: 1710
  - 38: 1800
  - 39: 1890
  - 40: 1980
  - 41: 2100
  - 42: